name: create_table_with_terraform

env:
  TF_VAR_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  TF_VAR_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  TF_VAR_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      database:
        description: 'Database name'
        required: true
        type: string
      schema:
        description: 'Schema name'
        required: true
        type: string
      table_name:
        description: 'Table name'
        required: true
        type: string

jobs:
  provision_and_create:
    name: Provision Resources and Create Table
    runs-on: ubuntu-latest

    env:
      TF_VAR_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          sudo apt-get update && sudo apt-get install -y curl gzip
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.2-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.2-linux_x86_64.bash
          
      - name: Test SnowSQL Installation
        run: ~/snowflake/snowsql -v

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: Set user-defined variables
        run: |
          echo "TF_VAR_database=${{ github.event.inputs.database }}" >> $GITHUB_ENV
          echo "TF_VAR_schema=${{ github.event.inputs.schema }}" >> $GITHUB_ENV
          echo "TF_VAR_table_name=${{ github.event.inputs.table_name }}" >> $GITHUB_ENV
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform

      - name: Create Table via SnowSQL
        run: |
          echo "Running SnowSQL Command..."
          export SNOWSQL_PWD=$SNOWFLAKE_PASSWORD
          ~/snowflake/snowsql \
            -a "$SNOWFLAKE_ACCOUNT" \
            -u "$SNOWFLAKE_USER" \
            -q "CREATE TABLE IF NOT EXISTS \"${{ github.event.inputs.database }}\".\"${{ github.event.inputs.schema }}\".\"${{ github.event.inputs.table_name }}\" (
                  id NUMBER,
                  name VARCHAR,
                  created_at TIMESTAMP_LTZ
                );"
