name: create_table_with_terraform

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      database:
        description: 'Database name'
        required: true
        type: string
      schema:
        description: 'Schema name'
        required: true
        type: string
      table_name:
        description: 'Table name'
        required: true
        type: string

jobs:
  provision_and_create:
    name: Provision Resources and Create Table
    runs-on: ubuntu-latest

    env:
      TF_VAR_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Environment Variables
        run: |
          echo "SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}"
          echo "SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}"
          echo "SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: Set user-defined variables
        run: |
          echo "TF_VAR_database=${{ github.event.inputs.database }}" >> $GITHUB_ENV
          echo "TF_VAR_schema=${{ github.event.inputs.schema }}" >> $GITHUB_ENV
          echo "TF_VAR_table_name=${{ github.event.inputs.table_name }}" >> $GITHUB_ENV
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
